export const styles = {
    colors: {
        backgroundMain: "#f5f5f5",
        backgroundSurface: "#74c3ff33",
        textMain: "#74c3ff",
        textMuted: "#74c3ff99",
        textBrightMain: "#e4f6fc",
        textBrightMuted: "#e4f6fc99",
        border: "#74c3ff",
        button: "#74c3ff",

        error: "#EF4444",
        errorBack: "#ffeaea",
        warning: "#F59E0B",
        warningBack: "#fff5e3",
        info: "#74c3ff",
        infoBack: "#ddf2ff",
    },
    radius: {
        xxs: 2,
        xs: 4,
        sm: 8,
        md: 12,
        lg: 16,
        xl: 20,
        xxl: 24,
    },
    spacing: {
        xxs: 4,
        xs: 8,
        sm: 12,
        md: 16,
        lg: 24,
        xl: 32,
        xxl: 40,
    },
};
